name: Pipeline

env:
  TAG_CONDITION: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm run init:all
          npm run build:ui
          npx playwright install --with-deps
      - name: Run linter
        run: npm run lint
      - name: Create .env
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_MONGODB_URL: ${{ secrets.MONGODB_URL }}
          envkey_TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_PORT: 3003
      - name: Test backend
        run: npm run server:test & npm run test:server
  test_frontend:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm run init:all
          npm run build:ui
          npx playwright install --with-deps
      - name: Create .env
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_MONGODB_URL: ${{ secrets.MONGODB_URL }}
          envkey_TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_PORT: 3003
      - name: Test frontend
        run: npm run test
  add_tag:
    needs: test_frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add tag
        if: ${{ github.event_name == 'push' && env.TAG_CONDITION == 'false' }}
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch