name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Initialize frontend and backend
      run: npm run init:all && npm run build:ui
    - name: actions-env
      uses: skiddph/actions-env@v1.0.3
      with:
        file: ./backend/.env
      env:
        TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
        SECRET: ${{ secrets.SECRET }}
        PORT: '3003'
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30